"""add_dossier_ref_to_scrutins

Revision ID: 72d9379f179d
Revises: fc168acbe10f
Create Date: 2026-04-02 19:45:54.461023+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "72d9379f179d"
down_revision: Union[str, None] = "fc168acbe10f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scrutins", sa.Column("dossier_ref", sa.String(length=50), nullable=True)
    )
    op.add_column("scrutins", sa.Column("dossier_libelle", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_scrutins_dossier_ref"), "scrutins", ["dossier_ref"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scrutins_dossier_ref"), table_name="scrutins")
    op.drop_column("scrutins", "dossier_libelle")
    op.drop_column("scrutins", "dossier_ref")
    # ### end Alembic commands ###
