"""add_dossier_ref_to_amendements

Revision ID: eea15b80cfa1
Revises: 72d9379f179d
Create Date: 2026-04-03 10:28:10.321265+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "eea15b80cfa1"
down_revision: Union[str, None] = "72d9379f179d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "amendements", sa.Column("dossier_ref", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_amendements_dossier_ref"),
        "amendements",
        ["dossier_ref"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_amendements_dossier_ref"), table_name="amendements")
    op.drop_column("amendements", "dossier_ref")
    # ### end Alembic commands ###
