"""organes libelle varchar 500

Revision ID: c2b4a9b5f7fa
Revises: b3c4d5e6f7a8
Create Date: 2026-04-09 20:03:26.884851+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c2b4a9b5f7fa"
down_revision: Union[str, None] = "b3c4d5e6f7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "amendements", sa.Column("dossier_ref", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_amendements_dossier_ref"), "amendements", ["dossier_ref"], unique=False
    )
    op.alter_column(
        "organes",
        "libelle",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organes",
        "libelle",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_amendements_dossier_ref"), table_name="amendements")
    op.drop_column("amendements", "dossier_ref")
    # ### end Alembic commands ###
