"""init schema

Revision ID: 59897fe08fa5
Revises: 
Create Date: 2026-03-23 20:22:41.337151+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "59897fe08fa5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organes",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("sigle", sa.String(length=20), nullable=False),
        sa.Column("libelle", sa.String(length=200), nullable=False),
        sa.Column("couleur", sa.String(length=7), nullable=True),
        sa.Column("legislature", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scrutins",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("titre", sa.Text(), nullable=False),
        sa.Column("date_seance", sa.Date(), nullable=False),
        sa.Column("type_vote", sa.String(length=50), nullable=True),
        sa.Column("sort", sa.String(length=20), nullable=True),
        sa.Column("nombre_votants", sa.Integer(), nullable=True),
        sa.Column("nombre_pours", sa.Integer(), nullable=True),
        sa.Column("nombre_contres", sa.Integer(), nullable=True),
        sa.Column("nombre_abstentions", sa.Integer(), nullable=True),
        sa.Column("url_an", sa.String(length=500), nullable=True),
        sa.Column("legislature", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scrutins_date_seance"), "scrutins", ["date_seance"], unique=False
    )
    op.create_table(
        "deputes",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("nom", sa.String(length=200), nullable=False),
        sa.Column("prenom", sa.String(length=100), nullable=False),
        sa.Column("nom_de_famille", sa.String(length=100), nullable=False),
        sa.Column("sexe", sa.String(length=1), nullable=True),
        sa.Column("date_naissance", sa.Date(), nullable=True),
        sa.Column("profession", sa.String(length=200), nullable=True),
        sa.Column("num_departement", sa.String(length=3), nullable=True),
        sa.Column("nom_circonscription", sa.String(length=200), nullable=True),
        sa.Column("num_circonscription", sa.Integer(), nullable=True),
        sa.Column("place_hemicycle", sa.Integer(), nullable=True),
        sa.Column("url_photo", sa.String(length=500), nullable=True),
        sa.Column("url_an", sa.String(length=500), nullable=True),
        sa.Column("twitter", sa.String(length=100), nullable=True),
        sa.Column("mandat_debut", sa.Date(), nullable=True),
        sa.Column("mandat_fin", sa.Date(), nullable=True),
        sa.Column("legislature", sa.Integer(), nullable=False),
        sa.Column("groupe_id", sa.String(length=50), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["groupe_id"],
            ["organes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "amendements",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("numero", sa.String(length=20), nullable=True),
        sa.Column("titre", sa.Text(), nullable=True),
        sa.Column("texte_legislature", sa.String(length=50), nullable=True),
        sa.Column("date_depot", sa.Date(), nullable=True),
        sa.Column("sort", sa.String(length=50), nullable=True),
        sa.Column("url_an", sa.String(length=500), nullable=True),
        sa.Column("depute_id", sa.String(length=50), nullable=True),
        sa.Column("legislature", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["depute_id"],
            ["deputes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_amendements_date_depot"), "amendements", ["date_depot"], unique=False
    )
    op.create_table(
        "votes_deputes",
        sa.Column("scrutin_id", sa.String(length=50), nullable=False),
        sa.Column("depute_id", sa.String(length=50), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["depute_id"],
            ["deputes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scrutin_id"],
            ["scrutins.id"],
        ),
        sa.PrimaryKeyConstraint("scrutin_id", "depute_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes_deputes")
    op.drop_index(op.f("ix_amendements_date_depot"), table_name="amendements")
    op.drop_table("amendements")
    op.drop_table("deputes")
    op.drop_index(op.f("ix_scrutins_date_seance"), table_name="scrutins")
    op.drop_table("scrutins")
    op.drop_table("organes")
    # ### end Alembic commands ###
