"""add social media fields to deputes

Revision ID: 1c2dc6336af1
Revises: 59897fe08fa5
Create Date: 2026-03-26 22:28:53.708729+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "1c2dc6336af1"
down_revision: Union[str, None] = "59897fe08fa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deputes", sa.Column("facebook_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "deputes", sa.Column("instagram_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "deputes", sa.Column("bluesky_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deputes", "bluesky_url")
    op.drop_column("deputes", "instagram_url")
    op.drop_column("deputes", "facebook_url")
    # ### end Alembic commands ###
